openapi: 3.0.3
info:
  title: NS-QRGameService
  version: 1.0.0
servers:
  - url: 'https://ns-qrgameservice.fly.dev/'

tags:
  - name: User
    description: ユーザー側API（ゲーム側からは触らない

  - name: Service
    description: ゲームサービスAPI（ゲーム側から触る部分）

  - name: System
    description: システム管理用（mono含める管理者以外触れない）

paths:
  /users/auth/login:
    get:
      tags:
        - User
      summary: "ユーザーログイン"
      description: "ユーザーのセッションを生成し返します"
      responses:
        200:
          description: "ログイン成功"
        500:
          description: "ログイン失敗"

  /users/getMoney:
    get:
      tags:
        - User
      summary: "ユーザー所持金取得"
      description: "ユーザーの所持金を取得します"
      responses:
        200:
          description: "所持金取得成功"
        500:
          description: "所持金取得失敗"

  /users/scanCode:
    post:
      tags:
        - User
      summary: "QRコードスキャン"
      description: "QRコードをスキャンし、結果を返します"
      responses:
        200:
          description: "スキャン成功"
        500:
          description: "スキャン失敗"

  /service/getGameService:
    post:
      tags:
        - Service
      summary: "ゲームサービス取得"
      description: "ゲームサービスを取得します"
      parameters:
        - in: header
          name: X-API-KEY
          schema:
            type: string
          required: true
          description: "配布されたAPIKey"
      responses:
        200:
          description: "ゲームサービス取得成功"
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: "成功かどうか"
                  data:
                    type: object
                    properties:
                      gameId:
                        type: string
                        description: "ゲームID"
                      adminUserId:
                        type: string
                        description: "管理者ユーザーID"
                      playMoney:
                        type: number
                        description: "プレイ料金"
                  error:
                    type: string
                    description: "エラーメッセージ"
        403:
          description: "APIKeyが不正"
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    additionalProperties: false
                    description: "成功かどうか"
                  data:
                    type: object
                  error:
                    type: string
                    description: "エラーメッセージ"

        500:
          description: "ゲームサービス取得失敗"

  /service/getUserInfo:
    post:
      tags:
        - Service
      summary: "ユーザー情報取得"
      description: "ユーザー情報を取得します"
      parameters:
        - in: header
          name: X-API-KEY
          schema:
            type: string
          required: true
          description: "配布されたAPIKey"
        - in: query
          name: body
          required: true
          content:
            application/json:
              schema:
                type: object
                properties:
                  uuid:
                    type: string
                    description: "ユーザーID"
              example:
                uuid: "user-1234"
      responses:
        200:
          description: "ユーザー情報取得成功"
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: "成功かどうか"
                  data:
                    type: object
                    properties:
                      uuid:
                        type: string
                        description: "ユーザーID"
                      userName:
                        type: string
                        description: "ユーザー名"
                      data:
                        type: object
                        description: "ゲームごとのユーザーデータ"
                  error:
                    type: string
                    description: "エラーメッセージ"
        403:
          description: "APIKeyが不正"
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    additionalProperties: false
                    description: "成功かどうか"
                  data:
                    type: object
                  error:
                    type: string
                    description: "エラーメッセージ"

        500:
          description: "ユーザー情報取得失敗"

  /service/setUserInfo:
    post:
      tags:
        - Service
      summary: "ユーザー情報設定"
      description: "ユーザー情報を設定します"
      parameters:
        - in: header
          name: X-API-KEY
          schema:
            type: string
          required: true
          description: "配布されたAPIKey"
        - in: query
          name: body
          required: true
          content:
            application/json:
              schema:
                type: object
                properties:
                  uuid:
                    type: string
                    description: "ユーザーID"
                  data:
                    type: object
                    description: "設定するデータ"
              example:
                uuid: "user-1234"
                data: {}
      responses:
        200:
          description: "ユーザー情報設定成功"
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: "成功かどうか"
                  data:
                    type: object
                    properties:
                      uuid:
                        type: string
                        description: "ユーザーID"
                      userInfo:
                        type: object
                        description: "ゲームごとのユーザーデータ"
                  error:
                    type: string
                    description: "エラーメッセージ"
        403:
          description: "APIKeyが不正"
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    additionalProperties: false
                    description: "成功かどうか"
                  data:
                    type: object
                  error:
                    type: string
                    description: "エラーメッセージ"

        500:
          description: "ユーザー情報設定失敗"

  /service/addUserPoint:
    post:
      tags:
        - Service
      summary: "ユーザーポイント追加"
      description: "ユーザーのポイントを追加します"
      parameters:
        - in: header
          name: X-API-KEY
          schema:
            type: string
          required: true
          description: "配布されたAPIKey"
        - in: query
          name: body
          required: true
          content:
            application/json:
              schema:
                type: object
                properties:
                  uuid:
                    type: string
                    description: "ユーザーID"
                  point:
                    type: number
                    description: "追加するポイント数"
              example:
                uuid: "user-1234"
                point: 50
      responses:
        200:
          description: "ユーザーポイント追加成功"
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: "成功かどうか"
                  data:
                    type: object
                    properties:
                      uuid:
                        type: string
                        description: "ユーザーID"
                      money:
                        type: number
                        description: "追加後のポイント数"
                  error:
                    type: string
                    description: "エラーメッセージ"

        403:
          description: "APIKeyが不正"
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    additionalProperties: false
                    description: "成功かどうか"
                  data:
                    type: object
                  error:
                    type: string
                    description: "エラーメッセージ"

        500:
          description: "ユーザーポイント追加失敗"

  /service/getCode:
    get:
      tags:
        - Service
      summary: "QRコード取得"
      description: "QRコードを取得します"
      parameters:
        - in: header
          name: X-API-KEY
          schema:
            type: string
          required: true
          description: "配布されたAPIKey"
      responses:
        200:
          description: "QRコード取得成功"
          content:
            application/json:
              schema:
                type: object
                properties:
                  loginCode:
                    type: string
                    description: "QRコード用のUUID"

        403:
          description: "APIKeyが不正"
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    additionalProperties: false
                    description: "成功かどうか"
                  data:
                    type: object
                  error:
                    type: string
                    description: "エラーメッセージ"

        500:
          description: "QRコード取得失敗"

  /service/getResultCode:
    post:
      tags:
        - Service
      summary: "QRコード結果取得"
      description: "QRコードの結果を取得します"
      parameters:
        - in: header
          name: X-API-KEY
          schema:
            type: string
          required: true
          description: "配布されたAPIKey"
        - in: query
          name: body
          required: true
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                    description: "QRコード結果"
              example:
                code: "QR1234"
      responses:
        200:
          description: "QRコード結果取得成功"
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: "成功かどうか"
                  data:
                    type: object
                    properties:
                      resultUUID:
                        type: string
                        description: "UUID"
                  error:
                    type: string
                    description: "エラーメッセージ"

        403:
          description: "APIKeyが不正"
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    additionalProperties: false
                    description: "成功かどうか"
                  data:
                    type: object
                  error:
                    type: string
                    description: "エラーメッセージ"

        500:
          description: "QRコード結果取得失敗"
